{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"view_city_bank_shutdowns_acquisitions\",\"view_economic_data_bank_shutdown\",\"prepared_failed_banks\",\"city_state\",\"economy_and_failed_banks_merged\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.952.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "6308a266-590d-470b-8639-fde13ae106fb",
        "fromColumn": "YEAR",
        "fromTable": "prepared_failed_banks",
        "toColumn": "Year",
        "toTable": "view_economic_data_bank_shutdown"
      },
      {
        "name": "6f5526f6-544e-44b9-a244-28d77c6c8f26",
        "fromColumn": "Date",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3aeea785-4218-440d-9ef3-edf9ed076d6c"
      },
      {
        "name": "df783ea5-c6ea-4ddd-82a0-04d72ea55199",
        "fromColumn": "City Affected",
        "fromTable": "prepared_failed_banks",
        "toColumn": "Bank Closure Cities",
        "toTable": "view_city_bank_shutdowns_acquisitions"
      },
      {
        "name": "cc36177c-ba9e-4cba-b351-83c0ede68a6f",
        "fromColumn": "Shutdown_Date",
        "fromTable": "prepared_failed_banks",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "18dc7ba2-43db-45ef-9edd-525288a8dd21",
        "fromColumn": "YEAR",
        "fromTable": "prepared_failed_banks",
        "toColumn": "Year",
        "toTable": "economy_and_failed_banks_merged"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_af82403c-de08-41ea-9b2d-aa78dbd5615a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e0a2d7a6-b62b-451c-8536-69b3680256f3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "83ada9df-b9bb-418d-8018-9d916f5b5222",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2f64fed1-6ebc-4fea-a1f4-e408fe995f2b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c78675d3-3975-4a13-be09-3635346a37e6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d4aff914-88a9-4245-a874-a657589babee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b618731e-94ad-4ddf-a6e9-af43b8c9ab82",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4554fe7a-f814-4330-b36e-beaeda729b90",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "463a4222-caed-4cb8-a3eb-982befdc0f90",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f7d82a2f-fae3-4763-bd8a-6401c51019dd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f6837cae-2ea7-47a4-96ba-9aaea8f4bacd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2556c8df-3849-4981-81e7-da43ddadf01d",
                "ordinal": 3
              }
            ],
            "lineageTag": "79d83786-6007-4a47-8c6c-8f148ab1b2dd"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b831958d-3bc2-44a9-9e45-90c29724bb60",
        "partitions": [
          {
            "name": "DateTableTemplate_af82403c-de08-41ea-9b2d-aa78dbd5615a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "view_city_bank_shutdowns_acquisitions",
        "columns": [
          {
            "name": "State Affected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd3998b1-161b-4717-93b5-101478a15f95",
            "sourceColumn": "State Affected",
            "summarizeBy": "none"
          },
          {
            "name": "Closures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "05a93e1b-0356-4947-b56c-9009baadbcbe",
            "sourceColumn": "Closures",
            "summarizeBy": "none"
          },
          {
            "name": "Acquisitions per State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b5bdd37-d5f9-4778-9713-7290b40f174f",
            "sourceColumn": "Acquisitions per State",
            "summarizeBy": "none"
          },
          {
            "name": "Not Acquired per State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "277e0680-a1c8-48ea-9a20-587d8d64f379",
            "sourceColumn": "Not Acquired per State",
            "summarizeBy": "none"
          },
          {
            "name": "Bank Closure Cities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7695e6d0-3589-42a5-a013-06b8ac0a705a",
            "sourceColumn": "Bank Closure Cities",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3e13f692-019b-4ca1-85c9-b617d0bc3ded",
        "partitions": [
          {
            "name": "view_city_bank_shutdowns_acquisitions",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_view_city_bank_shutdowns_acquisitions = Source{[Schema=\"dbo\",Item=\"view_city_bank_shutdowns_acquisitions\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_view_city_bank_shutdowns_acquisitions,{{\"Acquisitions_per_state\", \"Acquisitions per State\"}, {\"Cities_of_shutdowns_per_state\", \"Bank Closure Cities\"}, {\"Not_acquired_per_state\", \"Not Acquired per State\"}, {\"Count_of_Shutdowns\", \"Closures\"}, {\"state\", \"State Affected\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "view_economic_data_bank_shutdown",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "451db56d-a72c-4034-aa69-fdbbe341b2d6",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Closures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5035b82a-c691-4d97-82c2-08d9ea9b6c2c",
            "sourceColumn": "Closures",
            "summarizeBy": "none"
          },
          {
            "name": "Acquisitions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea2df85d-47b3-4b88-ba1f-c4e6f536cd1d",
            "sourceColumn": "Acquisitions",
            "summarizeBy": "none"
          },
          {
            "name": "Real Estate Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "276dbf5b-b123-4295-a4c3-81dde5f4c289",
            "sourceColumn": "Real Estate Loans % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Loans In Billions (Bank Credit)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e9106b3-1b94-4116-94f9-a975b6a994d6",
            "sourceColumn": "Consumer Loans In Billions (Bank Credit)",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Card Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "50a10c55-3abb-4d81-af02-90295aa54920",
            "sourceColumn": "Consumer Card Loans % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Loans In Billions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c8863185-a0c9-4f76-9b69-39fb8823fe0e",
            "sourceColumn": "Consumer Loans In Billions",
            "summarizeBy": "none"
          },
          {
            "name": "Borrowing % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "48e55c75-da8d-441f-ab45-3ecfc9a0855a",
            "sourceColumn": "Borrowing % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Bank Credit % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa1b7ed0-0f22-4ee6-8736-c0190a1bb63e",
            "sourceColumn": "Bank Credit % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Inflation to GDP Percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d38ea130-2b6f-404b-84a4-eef1c91c2933",
            "sourceColumn": "Inflation to GDP Percentage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "939a104c-9c40-4956-b4f2-6a45b0d762aa",
        "partitions": [
          {
            "name": "view_economic_data_bank_shutdown",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_view_economic_data_bank_shutdown = Source{[Schema=\"dbo\",Item=\"view_economic_data_bank_shutdown\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_view_economic_data_bank_shutdown,{{\"Bank_credit_Percent_Change\", \"Bank Credit % Change\"}, {\"Borrowings_Percentage_Change\", \"Borrowing % Change\"}, {\"Consumer_Card_Loans_Percent_Change\", \"Consumer Card Loans % Change\"}, {\"Consumer_Loans_In_Billions\", \"Consumer Loans In Billions\"}, {\"Consumer_Loans_In_Billions_Bank_Credit\", \"Consumer Loans In Billions (Bank Credit)\"}, {\"Inflation_GDP_Percentage\", \"Inflation GDP Percentage\"}, {\"Real_Estate_Loans_Percent_Change\", \"Real Estate Loans % Change\"}, {\"ShutDowns\", \"Shut Downs\"}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Renamed Columns\",{{\"Year\", Order.Ascending}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Sorted Rows\",{{\"Inflation GDP Percentage\", \"Inflation to GDP Percentage\"}, {\"Shut Downs\", \"Closures\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "prepared_failed_banks",
        "columns": [
          {
            "name": "Bank_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10230c09-418b-40fd-bfcf-dae79dc18923",
            "sourceColumn": "Bank_Name",
            "summarizeBy": "none"
          },
          {
            "name": "City Affected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6420694f-d80e-4d23-87ae-b24a41e5ff55",
            "sourceColumn": "City Affected",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c32ace64-380f-4948-bef2-06d960bf8b12",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Cert",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ce4f5f5-d3dc-40d7-a4c8-9c9b76b914b4",
            "sourceColumn": "Cert",
            "summarizeBy": "sum"
          },
          {
            "name": "Acquiring_Bank_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c791ed77-cda9-46c9-bd6b-2292672e6f37",
            "sourceColumn": "Acquiring_Bank_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Fund",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b55d156-697e-4aa2-8f88-9da697b96dfc",
            "sourceColumn": "Fund",
            "summarizeBy": "sum"
          },
          {
            "name": "Shutdown_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "6e553fcb-1341-4087-9490-5b55b9ba41b2",
            "sourceColumn": "Shutdown_Date",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc932887-2d85-4667-8c13-d7d193ff6617",
            "sourceColumn": "YEAR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5563eb4a-27bf-46ae-9b7c-aa47fed26971",
        "measures": [
          {
            "name": "Was Acquired?",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(COUNTX(prepared_failed_banks,prepared_failed_banks[Acquiring_Bank_ID]))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43d197af-f481-4ae5-a20d-71df722736dc"
          },
          {
            "name": "Was Acquired? (Yes/No)",
            "expression": "IF([Was Acquired?]>=1,\"Yes\",\"No\")",
            "lineageTag": "a125bdfa-1a51-474a-96b2-312e92555e3d"
          }
        ],
        "partitions": [
          {
            "name": "prepared_failed_banks",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_prepared_failed_banks = Source{[Schema=\"dbo\",Item=\"prepared_failed_banks\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_prepared_failed_banks,{{\"YEAR\", \"YEAR\"}, {\"City\", \"City Affected\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "city_state",
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7bfa9070-15e5-48b7-821c-127dfeee8572",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5d495b61-2b61-4a8b-8e55-39687c3f7627",
            "sourceColumn": "State",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "6c83b176-2a0f-41d0-81d0-d3ef676f5083",
        "partitions": [
          {
            "name": "city_state",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_city_state = Source{[Schema=\"dbo\",Item=\"city_state\"]}[Data]",
                "in",
                "    dbo_city_state"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "economy_and_failed_banks_merged",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "033c516c-73cb-4eb7-aa08-5979897f4069",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Bank Closures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60f81b91-f752-4a2c-81af-bb72e0aa0a69",
            "sourceColumn": "Bank Closures",
            "summarizeBy": "none"
          },
          {
            "name": "Acquisitions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e2ee8e5-c15b-472d-b4d9-15ac9243bf2d",
            "sourceColumn": "Acquisitions",
            "summarizeBy": "none"
          },
          {
            "name": "Real Estate Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1ddd7205-1129-4e57-9bdc-33e5004e9266",
            "sourceColumn": "Real Estate Loans % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Loans In Billions (Bank Credit)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e22a3e07-42e7-4901-81ad-15c949857155",
            "sourceColumn": "Consumer Loans In Billions (Bank Credit)",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Card Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2944024-9655-48b5-9c15-05ccc06b579d",
            "sourceColumn": "Consumer Card Loans % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Loans In Billions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ccbe381-48f8-4912-8ddf-a487e4e97b68",
            "sourceColumn": "Consumer Loans In Billions",
            "summarizeBy": "none"
          },
          {
            "name": "Borrowing % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d99b5912-76ab-4fb6-91d5-5e7ed16d1c8c",
            "sourceColumn": "Borrowing % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Bank Credit % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8cc4ad2f-5900-4857-99f0-b89f3ff3ddac",
            "sourceColumn": "Bank Credit % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Inflation GDP %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "553d7675-7953-4f1c-b6e1-ce6f31117f59",
            "sourceColumn": "Inflation GDP %",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6a78b46-7b1a-49c8-bdb3-2e26101da810",
        "partitions": [
          {
            "name": "economy_and_failed_banks_merged",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(view_economic_data_bank_shutdown, {\"Year\"}, prepared_failed_banks, {\"YEAR\"}, \"prepared_failed_banks\", JoinKind.Inner),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Inflation GDP Percentage\", \"Inflation GDP %\"}, {\"Shut Downs\", \"Bank Closures\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "59e6348db9224b85bb79d5a8a21c0a11"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6fccef27-8227-41bc-8adb-38db8c501225",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3aeea785-4218-440d-9ef3-edf9ed076d6c"
                },
                "isDefault": true,
                "relationship": "6f5526f6-544e-44b9-a244-28d77c6c8f26"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"FY\" & YEAR('Date'[Date])-IF(MONTH('Date'[Date])<10,1,0)",
            "isDataTypeInferred": true,
            "lineageTag": "87f95b40-5c79-4d62-8274-a1263a2a073a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date'[Date], \"YYYY mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "e8583b5e-cf26-4c48-a04d-11269599f078",
            "sortByColumn": "Month Key",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "YEAR('Date'[Date]) & IF(MONTH('Date'[Date])<4,\" Q2\",",
              "            IF(MONTH('Date'[Date])<7,\" Q3\",",
              "            IF(MONTH('Date'[Date])<10,\" Q4\",\" Q1\")))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "51b6a199-cf6c-4bca-88ea-00cc0761e914",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Date'[Date])*100+MONTH('Date'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "07605fca-71a5-405c-89d9-2b10ece81f60",
            "summarizeBy": "count",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Date'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9d95ded7-9190-42c8-983b-b094b2d00369",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "3e6c4190-df30-4d8c-aa11-fc471c0dad96",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": "CALENDARAUTO(9)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3aeea785-4218-440d-9ef3-edf9ed076d6c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aa0d8995-2a46-4c1d-86aa-f7a25773f1c0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2c14ca7e-a465-40ab-ab8d-624707a87ee8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f62a16b2-3caf-40b6-ae94-887caed3a179",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "17939d72-da08-40f2-8341-e91eabf9b916",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "198963e6-c579-4e9f-a484-711e81652909",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b186fa19-6549-47cd-957c-d504a874ce7c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "345cdee5-7fe7-401b-86da-6fe173bd6495",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "84b403a9-1338-4114-844b-8676f6522683",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5680c6b0-95ad-48a8-99c1-39457f7ec08f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ff3276b4-4c84-4269-bc34-4d33b55c3045",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "60f2e28f-ad12-4863-8702-da72b743dcb0",
                "ordinal": 3
              }
            ],
            "lineageTag": "5183784c-f9a9-496f-aa51-8aabab9e8131"
          }
        ],
        "isHidden": true,
        "lineageTag": "867c9a39-9c13-4f23-b91f-6494f0661d71",
        "partitions": [
          {
            "name": "LocalDateTable_3aeea785-4218-440d-9ef3-edf9ed076d6c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}