{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"view_city_bank_shutdowns_acquisitions\",\"view_economic_data_bank_shutdown\",\"prepared_failed_banks\",\"city_state\",\"economy_and_failed_banks_merged\",\"view_economic_data_bank_shutdown (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "38d28c37-31b4-4c95-8eca-0c28c5c37570",
        "fromColumn": "Shutdown_Date",
        "fromTable": "prepared_failed_banks",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_66634a3c-9d7c-4518-b949-df985d865758"
      },
      {
        "name": "35929e82-0917-4287-915e-0f3d82165c0d",
        "fromColumn": "State",
        "fromTable": "prepared_failed_banks",
        "toColumn": "State",
        "toTable": "view_city_bank_shutdowns_acquisitions"
      },
      {
        "name": "3e1aea55-0d1a-483b-81f9-87dfecf02d95",
        "fromColumn": "State",
        "fromTable": "city_state",
        "toColumn": "State",
        "toTable": "view_city_bank_shutdowns_acquisitions"
      },
      {
        "name": "514ce1b6-8b9e-4a17-9554-8176371c734b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "State",
        "fromTable": "prepared_failed_banks",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "State",
        "toTable": "city_state"
      },
      {
        "name": "6308a266-590d-470b-8639-fde13ae106fb",
        "fromColumn": "YEAR",
        "fromTable": "prepared_failed_banks",
        "toColumn": "Year",
        "toTable": "view_economic_data_bank_shutdown"
      },
      {
        "name": "5412b2b7-26fd-49f7-b595-7a1af677c377",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Year",
        "fromTable": "view_economic_data_bank_shutdown",
        "toColumn": "Year",
        "toTable": "economy_and_failed_banks_merged"
      },
      {
        "name": "523a2a5e-4f83-4c75-845c-82d244925b2e",
        "fromColumn": "YEAR",
        "fromTable": "prepared_failed_banks",
        "isActive": false,
        "toColumn": "Year",
        "toTable": "economy_and_failed_banks_merged"
      },
      {
        "name": "d6a9f157-8ee3-4965-9e33-1788b92a5740",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Year",
        "fromTable": "view_economic_data_bank_shutdown",
        "toColumn": "Year",
        "toTable": "view_economic_data_bank_shutdown (2)"
      },
      {
        "name": "4241d30c-9627-43a0-a5b2-0056a4edc98a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Year",
        "fromTable": "economy_and_failed_banks_merged",
        "isActive": false,
        "toColumn": "Year",
        "toTable": "view_economic_data_bank_shutdown (2)"
      },
      {
        "name": "2681040c-fcfc-4fbf-b60f-c69afb88104f",
        "fromColumn": "YEAR",
        "fromTable": "prepared_failed_banks",
        "isActive": false,
        "toColumn": "Year",
        "toTable": "view_economic_data_bank_shutdown (2)"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_af82403c-de08-41ea-9b2d-aa78dbd5615a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e0a2d7a6-b62b-451c-8536-69b3680256f3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "83ada9df-b9bb-418d-8018-9d916f5b5222",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2f64fed1-6ebc-4fea-a1f4-e408fe995f2b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c78675d3-3975-4a13-be09-3635346a37e6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d4aff914-88a9-4245-a874-a657589babee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b618731e-94ad-4ddf-a6e9-af43b8c9ab82",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4554fe7a-f814-4330-b36e-beaeda729b90",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "463a4222-caed-4cb8-a3eb-982befdc0f90",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f7d82a2f-fae3-4763-bd8a-6401c51019dd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f6837cae-2ea7-47a4-96ba-9aaea8f4bacd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2556c8df-3849-4981-81e7-da43ddadf01d",
                "ordinal": 3
              }
            ],
            "lineageTag": "79d83786-6007-4a47-8c6c-8f148ab1b2dd"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b831958d-3bc2-44a9-9e45-90c29724bb60",
        "partitions": [
          {
            "name": "DateTableTemplate_af82403c-de08-41ea-9b2d-aa78dbd5615a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "view_city_bank_shutdowns_acquisitions",
        "columns": [
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd3998b1-161b-4717-93b5-101478a15f95",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Shutdowns",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "05a93e1b-0356-4947-b56c-9009baadbcbe",
            "sourceColumn": "Shutdowns",
            "summarizeBy": "sum"
          },
          {
            "name": "Acquisitions per State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b5bdd37-d5f9-4778-9713-7290b40f174f",
            "sourceColumn": "Acquisitions per State",
            "summarizeBy": "sum"
          },
          {
            "name": "Not Acquired per State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "277e0680-a1c8-48ea-9a20-587d8d64f379",
            "sourceColumn": "Not Acquired per State",
            "summarizeBy": "sum"
          },
          {
            "name": "Shutdowns Cities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7695e6d0-3589-42a5-a013-06b8ac0a705a",
            "sourceColumn": "Shutdowns Cities",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3e13f692-019b-4ca1-85c9-b617d0bc3ded",
        "partitions": [
          {
            "name": "view_city_bank_shutdowns_acquisitions",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_view_city_bank_shutdowns_acquisitions = Source{[Schema=\"dbo\",Item=\"view_city_bank_shutdowns_acquisitions\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_view_city_bank_shutdowns_acquisitions,{{\"Acquisitions_per_state\", \"Acquisitions per State\"}, {\"Cities_of_shutdowns_per_state\", \"Shutdowns Cities\"}, {\"Not_acquired_per_state\", \"Not Acquired per State\"}, {\"Count_of_Shutdowns\", \"Shutdowns\"}, {\"state\", \"State\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "view_economic_data_bank_shutdown",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "451db56d-a72c-4034-aa69-fdbbe341b2d6",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Shut Downs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5035b82a-c691-4d97-82c2-08d9ea9b6c2c",
            "sourceColumn": "Shut Downs",
            "summarizeBy": "none"
          },
          {
            "name": "Acquisitions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea2df85d-47b3-4b88-ba1f-c4e6f536cd1d",
            "sourceColumn": "Acquisitions",
            "summarizeBy": "none"
          },
          {
            "name": "Real Estate Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "276dbf5b-b123-4295-a4c3-81dde5f4c289",
            "sourceColumn": "Real Estate Loans % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Loans In Billions (Bank Credit)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e9106b3-1b94-4116-94f9-a975b6a994d6",
            "sourceColumn": "Consumer Loans In Billions (Bank Credit)",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Card Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "50a10c55-3abb-4d81-af02-90295aa54920",
            "sourceColumn": "Consumer Card Loans % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Consumer Loans In Billions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c8863185-a0c9-4f76-9b69-39fb8823fe0e",
            "sourceColumn": "Consumer Loans In Billions",
            "summarizeBy": "none"
          },
          {
            "name": "Borrowing % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "48e55c75-da8d-441f-ab45-3ecfc9a0855a",
            "sourceColumn": "Borrowing % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Bank Credit % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa1b7ed0-0f22-4ee6-8736-c0190a1bb63e",
            "sourceColumn": "Bank Credit % Change",
            "summarizeBy": "none"
          },
          {
            "name": "Inflation to GDP Percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d38ea130-2b6f-404b-84a4-eef1c91c2933",
            "sourceColumn": "Inflation to GDP Percentage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "939a104c-9c40-4956-b4f2-6a45b0d762aa",
        "partitions": [
          {
            "name": "view_economic_data_bank_shutdown",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_view_economic_data_bank_shutdown = Source{[Schema=\"dbo\",Item=\"view_economic_data_bank_shutdown\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_view_economic_data_bank_shutdown,{{\"Bank_credit_Percent_Change\", \"Bank Credit % Change\"}, {\"Borrowings_Percentage_Change\", \"Borrowing % Change\"}, {\"Consumer_Card_Loans_Percent_Change\", \"Consumer Card Loans % Change\"}, {\"Consumer_Loans_In_Billions\", \"Consumer Loans In Billions\"}, {\"Consumer_Loans_In_Billions_Bank_Credit\", \"Consumer Loans In Billions (Bank Credit)\"}, {\"Inflation_GDP_Percentage\", \"Inflation GDP Percentage\"}, {\"Real_Estate_Loans_Percent_Change\", \"Real Estate Loans % Change\"}, {\"ShutDowns\", \"Shut Downs\"}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Renamed Columns\",{{\"Year\", Order.Ascending}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Sorted Rows\",{{\"Inflation GDP Percentage\", \"Inflation to GDP Percentage\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "prepared_failed_banks",
        "columns": [
          {
            "name": "Bank_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10230c09-418b-40fd-bfcf-dae79dc18923",
            "sourceColumn": "Bank_Name",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6420694f-d80e-4d23-87ae-b24a41e5ff55",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c32ace64-380f-4948-bef2-06d960bf8b12",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Cert",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ce4f5f5-d3dc-40d7-a4c8-9c9b76b914b4",
            "sourceColumn": "Cert",
            "summarizeBy": "sum"
          },
          {
            "name": "Acquiring_Bank_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c791ed77-cda9-46c9-bd6b-2292672e6f37",
            "sourceColumn": "Acquiring_Bank_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Fund",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b55d156-697e-4aa2-8f88-9da697b96dfc",
            "sourceColumn": "Fund",
            "summarizeBy": "sum"
          },
          {
            "name": "Shutdown_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6e553fcb-1341-4087-9490-5b55b9ba41b2",
            "sourceColumn": "Shutdown_Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_66634a3c-9d7c-4518-b949-df985d865758"
                },
                "isDefault": true,
                "relationship": "38d28c37-31b4-4c95-8eca-0c28c5c37570"
              }
            ]
          },
          {
            "name": "YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc932887-2d85-4667-8c13-d7d193ff6617",
            "sourceColumn": "YEAR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5563eb4a-27bf-46ae-9b7c-aa47fed26971",
        "partitions": [
          {
            "name": "prepared_failed_banks",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_prepared_failed_banks = Source{[Schema=\"dbo\",Item=\"prepared_failed_banks\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_prepared_failed_banks,{{\"YEAR\", \"YEAR\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_66634a3c-9d7c-4518-b949-df985d865758",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ff342bb6-4ddb-4560-bfdb-244d0f9c95b3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bcdb5166-be44-4b24-aa5e-353b56402a65",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f87a5f30-4344-4785-82d0-243764ac33fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "56491c39-a226-4950-9e34-4139ce7fd8f6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "840fa76a-3d75-4363-bdc5-5f2fe68bca04",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8a4b2fe3-f493-4c1e-b319-9f0036b7178a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc025ec9-b232-4fcc-9241-4259b1232fed",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5fa276d8-dcc5-4e0d-951f-bb7a71469f5f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "47c3026a-1c56-4bf9-859a-55902855a0c9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9aa95c68-f872-4514-b3e4-9c8abdb2a373",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d3c7b360-03c3-471b-9e14-50f6f20004a1",
                "ordinal": 3
              }
            ],
            "lineageTag": "2807fab2-2fea-4159-abbb-204d660008f1"
          }
        ],
        "isHidden": true,
        "lineageTag": "d5a9673b-80df-4dec-a8dd-7027c8a09a9d",
        "partitions": [
          {
            "name": "LocalDateTable_66634a3c-9d7c-4518-b949-df985d865758",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('prepared_failed_banks'[Shutdown_Date])), 1, 1), Date(Year(MAX('prepared_failed_banks'[Shutdown_Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "city_state",
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bfa9070-15e5-48b7-821c-127dfeee8572",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d495b61-2b61-4a8b-8e55-39687c3f7627",
            "sourceColumn": "State",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6c83b176-2a0f-41d0-81d0-d3ef676f5083",
        "partitions": [
          {
            "name": "city_state",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_city_state = Source{[Schema=\"dbo\",Item=\"city_state\"]}[Data]",
                "in",
                "    dbo_city_state"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "economy_and_failed_banks_merged",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "033c516c-73cb-4eb7-aa08-5979897f4069",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Shut Downs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60f81b91-f752-4a2c-81af-bb72e0aa0a69",
            "sourceColumn": "Shut Downs",
            "summarizeBy": "sum"
          },
          {
            "name": "Acquisitions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e2ee8e5-c15b-472d-b4d9-15ac9243bf2d",
            "sourceColumn": "Acquisitions",
            "summarizeBy": "sum"
          },
          {
            "name": "Real Estate Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1ddd7205-1129-4e57-9bdc-33e5004e9266",
            "sourceColumn": "Real Estate Loans % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Consumer Loans In Billions (Bank Credit)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e22a3e07-42e7-4901-81ad-15c949857155",
            "sourceColumn": "Consumer Loans In Billions (Bank Credit)",
            "summarizeBy": "sum"
          },
          {
            "name": "Consumer Card Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2944024-9655-48b5-9c15-05ccc06b579d",
            "sourceColumn": "Consumer Card Loans % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Consumer Loans In Billions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ccbe381-48f8-4912-8ddf-a487e4e97b68",
            "sourceColumn": "Consumer Loans In Billions",
            "summarizeBy": "sum"
          },
          {
            "name": "Borrowing % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d99b5912-76ab-4fb6-91d5-5e7ed16d1c8c",
            "sourceColumn": "Borrowing % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Bank Credit % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8cc4ad2f-5900-4857-99f0-b89f3ff3ddac",
            "sourceColumn": "Bank Credit % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Inflation GDP %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "553d7675-7953-4f1c-b6e1-ce6f31117f59",
            "sourceColumn": "Inflation GDP %",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f6a78b46-7b1a-49c8-bdb3-2e26101da810",
        "partitions": [
          {
            "name": "economy_and_failed_banks_merged",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(view_economic_data_bank_shutdown, {\"Year\"}, prepared_failed_banks, {\"YEAR\"}, \"prepared_failed_banks\", JoinKind.Inner),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Inflation GDP Percentage\", \"Inflation GDP %\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "view_economic_data_bank_shutdown (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b7f499b-9924-4992-bd0e-6c5ba7cd2050",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "ShutDowns",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c4c7a8f-696b-4ce1-b276-aab4df8f2a39",
            "sourceColumn": "ShutDowns",
            "summarizeBy": "sum"
          },
          {
            "name": "Acquisitions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f226eb10-dcc5-4faf-8db1-9139a1154079",
            "sourceColumn": "Acquisitions",
            "summarizeBy": "sum"
          },
          {
            "name": "Real Estate Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2bc0472-9073-4997-9093-b87ebeb3f320",
            "sourceColumn": "Real Estate Loans % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Consumer Loans (Billions)- Bank Credit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "76edcb8f-e676-464e-b384-fc421ccd8344",
            "sourceColumn": "Consumer Loans (Billions)- Bank Credit",
            "summarizeBy": "sum"
          },
          {
            "name": "Consumer Card Loans % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27bcfd0f-aeda-4de1-a701-810304c05020",
            "sourceColumn": "Consumer Card Loans % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Consumer Loans (Billions)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8aa9a906-4df1-4de4-98c7-b02617b46c7f",
            "sourceColumn": "Consumer Loans (Billions)",
            "summarizeBy": "sum"
          },
          {
            "name": "Borrowings % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcca29af-2ceb-459f-89e3-a57d374b71d3",
            "sourceColumn": "Borrowings % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Bank Credit % Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "db691be7-d065-46a7-baed-269ead477f1d",
            "sourceColumn": "Bank Credit % Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Inflation GDP %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fdd25e1c-95f3-44d7-a9fe-850aeb5dfb0c",
            "sourceColumn": "Inflation GDP %",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a100c4e9-b752-4bdb-aeaa-e27daca59533",
        "partitions": [
          {
            "name": "view_economic_data_bank_shutdown (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS\", \"us_banks-database\"),",
                "    dbo_view_economic_data_bank_shutdown = Source{[Schema=\"dbo\",Item=\"view_economic_data_bank_shutdown\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_view_economic_data_bank_shutdown,{{\"Real_Estate_Loans_Percent_Change\", \"Real Estate Loans % Change\"}, {\"Consumer_Loans_In_Billions_Bank_Credit\", \"Consumer Loans (Billions)- Bank Credit\"}, {\"Consumer_Card_Loans_Percent_Change\", \"Consumer Card Loans % Change\"}, {\"Consumer_Loans_In_Billions\", \"Consumer Loans (Billions)\"}, {\"Borrowings_Percentage_Change\", \"Borrowings % Change\"}, {\"Bank_credit_Percent_Change\", \"Bank Credit % Change\"}, {\"Inflation_GDP_Percentage\", \"Inflation GDP %\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}